### ISSUE TITLE
Improper host grouping in hosts file

### ISSUE THREAD

**Issue by christopherpaquin** [OOsemka/ansible-overcloud-inventory#1]
Been using this a lot, but have noticed I need to do a bit of cleanup to the hosts file.

Example below - all hosts seen as comp2 and comp1

[comp2]
tpavpcloud-comp22 ansible_ssh_host=172.20.4.114
tpavpcloud-comp23 ansible_ssh_host=172.20.4.119
tpavpcloud-comp20 ansible_ssh_host=172.20.4.111
tpavpcloud-comp21 ansible_ssh_host=172.20.4.129
tpavpcloud-comp2 ansible_ssh_host=172.20.4.103

[comp1]
tpavpcloud-comp18 ansible_ssh_host=172.20.4.132
tpavpcloud-comp19 ansible_ssh_host=172.20.4.128
tpavpcloud-comp17 ansible_ssh_host=172.20.4.122
tpavpcloud-comp16 ansible_ssh_host=172.20.4.101
tpavpcloud-comp13 ansible_ssh_host=172.20.4.116
tpavpcloud-comp14 ansible_ssh_host=172.20.4.125
tpavpcloud-comp11 ansible_ssh_host=172.20.4.126
tpavpcloud-comp12 ansible_ssh_host=172.20.4.124
tpavpcloud-comp10 ansible_ssh_host=172.20.4.121
tpavpcloud-comp1 ansible_ssh_host=172.20.4.102

**Comment by OOsemka** [comment]
Thanks Chris!

Yeah, I need to fix the script for this use case. This happens when you use "-" in your stack name. I have noticed this issue before. It was on my list to fix, but just didn't get to it yet

**Comment by OOsemka** [comment]
I believe this should be fixed now
